version: '3'
services:
  mysql:
    hostname: mysql
    container_name: mysql
    build:
      context: ./database
      args:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
  backend-java:
    build: ./Java-Backend/
    ports:
     - "8080:8080"
    depends_on:
     - mysql
    links:
     - mysql
    