version: '3'
services:
  db:
    build:
      context: ./database
      args:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
          - "${MYSQL_PORT}:3306" #For Local Development
    restart: always
  backend-java:
    build: ./Java-Backend/
    ports:
     - "8080:8080"
    depends_on:
     - db
    links:
     - db
  