version: '3'
services:
  mysql:
    hostname: mysql
    container_name: mysql
    build:
      context: ./Database
      args:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  backend-java:
    build: ./Java-Backend/
    ports:
     - "8080:8080"
    depends_on:
     - mysql
    links:
     - mysql
  # kwikemart:
  #   image: kwikemart
  #   build:  
  #     context: ./Dotnet-Backend
  #     dockerfile: Dockerfile
  #   depends_on:
  #       - mysql
  #   links:
  #     - mysql
  #   ports:
  #     - "8000:80"

volumes:
  db-data:
    